PREFIX ns1: <http://data.barcelona.cat/att/>
PREFIX ns2: <http://data.barcelona.cat/rel/>
# Todas las actividades con su titulo, tipo, precio, fechaInicio y fechaFin con su respectivo organizador.
SELECT ?actividad ?titulo ?tipo ?precio ?fechaInicio ?fechaFin ?organizador
WHERE {
  ?actividad a <http://data.barcelona.cat/actividades/Actividad> ;
            ns1:titulo ?titulo ;
            ns1:tipo ?tipo ;
            ns1:Precio ?precio ;
            ns1:fechaInicio ?fechaInicio ;
            ns1:fechaFin ?fechaFin ;
  			ns2:isHosted ?organizador .
}
ORDER BY ?fechaInicio






# Contea las actividades gratuitas (gratuïta) y las de pago (pagament)

SELECT ?tipo (COUNT(*) as ?cantidad)
WHERE {
  ?actividad a <http://data.barcelona.cat/actividades/Actividad> ;
            ns1:tipo ?tipo .
}
GROUP BY ?tipo



# Ver todas las relaciones utilizadas en el dataset

SELECT DISTINCT ?predicado (COUNT(*) as ?uso)
WHERE {
  ?s ?predicado ?o .
  FILTER(STRSTARTS(STR(?predicado), "http://data.barcelona.cat/rel/"))
}
GROUP BY ?predicado
ORDER BY DESC(?uso)






#"Mapa de calor" de la oferta de actividades segun localización (tendria que funcionar cuando la relacion ns2:isContained funcione)
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ns1: <http://data.barcelona.cat/att/>
PREFIX ns2: <http://data.barcelona.cat/rel/>

SELECT ?municipio ?organizador ?categoria
       (COUNT(?actividad) as ?numActividades)
       (SUM(xsd:integer(?aforo)) as ?aforoAcumulado)
       (GROUP_CONCAT(DISTINCT ?titulo; SEPARATOR="; ") as ?ejemplosActividades)
WHERE {
  ?actividad a <http://data.barcelona.cat/actividades/Actividad> ;
             ns1:titulo ?titulo ;
             ns1:Aforo ?aforo ;
             ns2:isHosted ?organizador ;
             ns2:typeOf ?categoria ;
             ns2:placed ?municipio .
  
}
GROUP BY ?comarca ?municipio ?organizador ?categoria
HAVING (COUNT(?actividad) >= 1)
ORDER BY ?comarca ?municipio ?organizador DESC(?numActividades)





# Dada un conjunto de Actividades, encontrar sus correspondientes organizadores
PREFIX ns1: <http://data.barcelona.cat/att/>
PREFIX ns2: <http://data.barcelona.cat/rel/>

SELECT ?actividad ?organizador
WHERE {
  ?actividad a <http://data.barcelona.cat/actividades/Actividad> ;
             ns2:isHosted ?organizador .
}
LIMIT 20





# Dado un conjunto de Municipio, encontrar la Comarca en la que está contenida (isContained)

PREFIX rel: <http://data.barcelona.cat/rel/>

SELECT ?municipio ?comarca
WHERE {
  ?municipio rel:isContained ?comarca .
}
ORDER BY ?municipio
LIMIT 20




# Dado un conjunto de Municipio, encontrar las Actividad correspondientes (placed)

PREFIX rel: <http://data.barcelona.cat/rel/>

SELECT ?municipio ?actividad
WHERE {
  ?actividad a <http://data.barcelona.cat/actividades/Actividad> ;
             rel:placed ?municipio ;
}
ORDER BY ?municipio
LIMIT 20