# -*- coding: utf-8 -*-
"""Task06_2025.ipynb

Automatically generated by Colab.

**Task 06: Modifying RDF(s)**
"""

#!pip install rdflib
#!wget https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)



"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

ontology = Namespace("http://oeg.fi.upm.es/def/people#")  
person = Namespace("http://oeg.fi.upm.es/resource/person/")
organization = Namespace("http://oeg.fi.upm.es/resource/organization/") 
g.namespace_manager.bind('ontology', ontology)
g.namespace_manager.bind('person', person)
g.namespace_manager.bind('organization', organization)

# this task is validated in the next step



"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**"""

g.add((ontology.Person, RDF.type, RDFS.Class))
g.add((ontology.Researcher, RDF.type, RDFS.Class))
g.add((ontology.AssociateProfessor, RDF.type, RDFS.Class))
g.add((ontology.FullProfessor, RDF.type, RDFS.Class))
g.add((ontology.InterimAssociateProfessor, RDF.type, RDFS.Class))

g.add((ontology.Person, RDFS.label, Literal("Person", datatype=XSD.string)))
g.add((ontology.Researcher, RDFS.label, Literal("Researcher", datatype=XSD.string)))
g.add((ontology.AssociateProfessor, RDFS.label, Literal("AssociateProfessor", datatype=XSD.string)))
g.add((ontology.FullProfessor, RDFS.label, Literal("FullProfessor", datatype=XSD.string)))
g.add((ontology.InterimAssociateProfessor, RDFS.label, Literal("InterimAssociateProfessor", datatype=XSD.string)))

# TO DO
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)



"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate**"""

g.add((ontology.hasColleague, RDF.type, RDF.Property))
g.add((ontology.hasColleague, RDFS.domain, ontology.Person))
g.add((ontology.hasColleague, RDFS.range, ontology.Person))
g.add((ontology.hasColleague, RDFS.label, Literal("hasColleague", datatype=XSD.string)))

g.add((ontology.hasName, RDF.type, RDF.Property))
g.add((ontology.hasName, RDFS.domain, ontology.Person))
g.add((ontology.hasName, RDFS.range, XSD.string))
g.add((ontology.hasName, RDFS.label, Literal("hasName", datatype=XSD.string)))

g.add((ontology.hasHomePage, RDF.type, RDF.Property))
g.add((ontology.hasHomePage, RDFS.domain, ontology.Person))
g.add((ontology.hasHomePage, RDFS.range, XSD.string))
g.add((ontology.hasHomePage, RDFS.label, Literal("hasHomePage", datatype=XSD.string)))

# TO DO
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)



"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

g.add((person.Raul, RDF.type, ontology.Person))
g.add((person.Asun, RDF.type, ontology.Person))
g.add((person.Oscar, RDF.type, ontology.Person))

g.add((person.Raul, RDFS.label, Literal("Raul", datatype=XSD.string)))
g.add((person.Asun, RDFS.label, Literal("Asun", datatype=XSD.string)))
g.add((person.Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))

g.add((person.Raul, ontology.hasColleague, person.Asun))
g.add((person.Asun, ontology.hasColleague, person.Raul))
g.add((person.Oscar, ontology.hasColleague, person.Asun))
g.add((person.Oscar, ontology.hasName, Literal("Oscar Corcho Garcia", datatype=XSD.string)))
g.add((person.Asun, ontology.hasHomePage, Literal("http://www.oeg-upm.net/", datatype=XSD.string)))

# TO DO
# Visualize the results
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)



"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 5 to describe Sarah and john (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf)**"""

g.add((ontology.hasEmail, RDF.type, RDF.Property))
g.add((ontology.hasEmail, RDFS.domain, ontology.Person))
g.add((ontology.hasEmail, RDFS.range, XSD.string))
g.add((ontology.hasEmail, RDFS.label, Literal("hasEmail", datatype=XSD.string)))

g.add((ontology.givenName, RDF.type, RDF.Property))
g.add((ontology.givenName, RDFS.domain, ontology.Person))
g.add((ontology.givenName, RDFS.range, XSD.string))

g.add((ontology.familyName, RDF.type, RDF.Property))
g.add((ontology.familyName, RDFS.domain, ontology.Person))
g.add((ontology.familyName, RDFS.range, XSD.string))

g.add((person.Oscar, ontology.hasEmail, Literal("ocorcho@fi.upm.es", datatype=XSD.string)))
g.add((person.Oscar, ontology.givenName, Literal("Oscar", datatype=XSD.string)))
g.add((person.Oscar, ontology.familyName, Literal("Corcho", datatype=XSD.string)))

# TO DO
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")
