# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Marquitos04/Curso2025-2026/blob/master/Assignment4/course_materials/notebooks/Task07.ipynb

**Task 07: Querying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# TO DO
# Visualize the results
result = [] #list of tuples
classes = set(g.subjects(RDF.type, RDFS.Class))
for c in classes:
    supers = list(g.objects(c, RDFS.subClassOf))
    if supers:
        for s in supers:
            result.append((c, s))
    else:
        result.append((c, None))
for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query = """
SELECT DISTINCT ?c ?sc
WHERE {
  ?c a rdfs:Class .
  OPTIONAL { ?c rdfs:subClassOf ?sc. }
}
"""

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

# variable to return
individuals = []
to_check = {ns.Person}
visited = set()

while to_check:
    cls = to_check.pop()
    visited.add(cls)
    # add subclasses
    for sub in g.subjects(RDFS.subClassOf, cls):
        if sub not in visited:
            to_check.add(sub)

# find instances of each class
for c in visited:
    for inst in g.subjects(RDF.type, c):
        if inst not in individuals:
            individuals.append(inst)
# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query = """
SELECT DISTINCT ?ind
WHERE {
  ?ind a ?cls .
  ?cls rdfs:subClassOf* <http://oeg.fi.upm.es/def/people#Person> .
}
"""
for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query = """
SELECT DISTINCT ?name ?type WHERE {
  ?s <http://oeg.fi.upm.es/def/people#knows> <http://oeg.fi.upm.es/def/people#Rocky> .
  ?s a ?type .
  OPTIONAL { ?s <http://oeg.fi.upm.es/def/people#hasName> ?name . }
  OPTIONAL { ?s rdfs:label ?name . }
}
"""
# TO DO
# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query = """
SELECT DISTINCT ?name WHERE {
  {
    ?person <http://oeg.fi.upm.es/def/people#hasColleague> ?col1 .
    ?col1 <http://oeg.fi.upm.es/def/people#ownsPet> ?pet1 .
    ?pet1 a <http://oeg.fi.upm.es/def/people#Animal> .
  }
  UNION
  {
    ?person <http://oeg.fi.upm.es/def/people#hasColleague> ?col2 .
    ?col2 <http://oeg.fi.upm.es/def/people#hasColleague> ?col3 .
    ?col3 <http://oeg.fi.upm.es/def/people#ownsPet> ?pet2 .
    ?pet2 a <http://oeg.fi.upm.es/def/people#Animal> .
  }

  OPTIONAL { ?person <http://oeg.fi.upm.es/def/people#hasName> ?name . }
  OPTIONAL { ?person rdfs:label ?name . }
}
"""

for r in g.query(query):
  print(r.name)

# TO DO
# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")