# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZMO3-UDvOmPv60k_OQu5f7hf99cYcnq

**Task 06: Modifying RDF(s)**
"""

# !pip install rdflib
# !wget https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

ONT = Namespace("http://oeg.fi.upm.es/def/people#")
PER = Namespace("http://oeg.fi.upm.es/resource/person/")

g.namespace_manager.bind("ontology", ONT)
g.namespace_manager.bind("person", PER)

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

g.add((ONT.Person, RDF.type, RDFS.Class))
g.add((ONT.Professor, RDF.type, RDFS.Class))
g.add((ONT.AssociateProfessor, RDF.type, RDFS.Class))
g.add((ONT.InterimAssociateProfessor, RDF.type, RDFS.Class))
g.add((ONT.FullProfessor, RDF.type, RDFS.Class))

g.add((ONT.Person, RDFS.label, Literal("Person", datatype=XSD.string)))
g.add((ONT.Professor, RDFS.label, Literal("Professor", datatype=XSD.string)))
g.add((ONT.AssociateProfessor, RDFS.label, Literal("AssociateProfessor", datatype=XSD.string)))
g.add((ONT.InterimAssociateProfessor, RDFS.label, Literal("InterimAssociateProfessor", datatype=XSD.string)))
g.add((ONT.FullProfessor, RDFS.label, Literal("FullProfessor", datatype=XSD.string)))

g.add((ONT.Professor, RDFS.subClassOf, ONT.Person))
g.add((ONT.AssociateProfessor, RDFS.subClassOf, ONT.Professor))
g.add((ONT.InterimAssociateProfessor, RDFS.subClassOf, ONT.AssociateProfessor))
g.add((ONT.FullProfessor, RDFS.subClassOf, ONT.Professor))

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate**"""

from rdflib.namespace import RDF, RDFS, XSD

targets = {
    ONT.hasColleague: "hasColleague",
    ONT.hasName: "hasName",
    ONT.hasHomePage: "hasHomePage",
}

for s in targets:
    g.set((s, RDF.type, RDF.Property))
for s, label in targets.items():
    for old in list(g.objects(s, RDFS.label)):
        g.remove((s, RDFS.label, old))
    g.add((s, RDFS.label, Literal(label, datatype=XSD.string)))

g.set((ONT.hasColleague, RDFS.domain, ONT.Person))
g.set((ONT.hasColleague, RDFS.range,  ONT.Person))

g.set((ONT.hasName,     RDFS.domain, ONT.Person))
g.set((ONT.hasName,     RDFS.range,  RDFS.Literal))

g.set((ONT.hasHomePage, RDFS.domain, ONT.FullProfessor))
g.set((ONT.hasHomePage, RDFS.range,  RDFS.Literal))

for s in targets:
    lab = g.value(s, RDFS.label)
    print("OK:", s, "->", lab, "datatype:", getattr(lab, "datatype", None))

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

g.add((PER.Oscar, RDF.type, ONT.Person))
g.add((PER.Asun,  RDF.type, ONT.FullProfessor))
g.add((PER.Raul,  RDF.type, ONT.Person))

g.add((PER.Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))
g.add((PER.Asun,  RDFS.label, Literal("Asun",  datatype=XSD.string)))
g.add((PER.Raul,  RDFS.label, Literal("Raul",  datatype=XSD.string)))

g.add((PER.Oscar, ONT.hasColleague, PER.Asun))

g.add((PER.Asun,  ONT.hasColleague, PER.Oscar))

g.add((PER.Oscar, ONT.hasName, Literal("Oscar N.", datatype=XSD.string)))

g.add((PER.Asun, ONT.hasHomePage, Literal("https://example.org/asun", datatype=XSD.string)))

r.validate_task_06_03(g)

# TASK 6.4: Add to the individual person:Oscar the email address, given and family names. 
# Use the properties already included in example 5 to describe Sarah and john 
# (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf)**

from rdflib import Namespace
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
FOAF  = Namespace("http://xmlns.com/foaf/0.1/")

g.add((PER.Oscar, VCARD.Given,  Literal("Oscar",  datatype=XSD.string)))
g.add((PER.Oscar, VCARD.Family, Literal("Navarro", datatype=XSD.string)))
g.add((PER.Oscar, FOAF.email,   Literal("oscar@oeg.fi.upm.es", datatype=XSD.string)))

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")